-- Questions Débutant - Europe
INSERT INTO questions (question_text, options, correct_answer, category, difficulty, type) VALUES
('Quelle est la capitale de la France ?', '["Paris", "Lyon", "Marseille", "Bordeaux"]', 'Paris', 'Europe', 'Beginner', 'text'),
('Dans quel pays se trouve la Tour de Pise ?', '["Italie", "Espagne", "Grèce", "France"]', 'Italie', 'Europe', 'Beginner', 'text'),
('Quelle est la monnaie utilisée en Allemagne ?', '["Euro", "Mark", "Livre", "Franc"]', 'Euro', 'Europe', 'Beginner', 'text'),
('Quel pays a la forme d''une botte ?', '["Italie", "Portugal", "Norvège", "Pologne"]', 'Italie', 'Europe', 'Beginner', 'text'),
('Quel est le plus grand pays d''Europe (et du monde) ?', '["Russie", "Ukraine", "France", "Allemagne"]', 'Russie', 'Europe', 'Beginner', 'text'),
('Quelle est la capitale de l''Espagne ?', '["Madrid", "Barcelone", "Séville", "Valence"]', 'Madrid', 'Europe', 'Beginner', 'text'),
('Où se trouve le Colisée ?', '["Rome", "Athènes", "Paris", "Londres"]', 'Rome', 'Europe', 'Beginner', 'text'),
('Quel est le drapeau avec une croix blanche sur fond rouge ?', '["Suisse", "Danemark", "Norvège", "Suède"]', 'Suisse', 'Europe', 'Beginner', 'text'),
('Quelle est la capitale du Royaume-Uni ?', '["Londres", "Manchester", "Liverpool", "Édimbourg"]', 'Londres', 'Europe', 'Beginner', 'text'),
('Quel pays est connu pour ses fjords ?', '["Norvège", "Danemark", "Pays-Bas", "Belgique"]', 'Norvège', 'Europe', 'Beginner', 'text'),
('Quelle est la capitale de l''Allemagne ?', '["Berlin", "Munich", "Hambourg", "Francfort"]', 'Berlin', 'Europe', 'Beginner', 'text'),
('Quel pays est célèbre pour l''Acropole ?', '["Grèce", "Italie", "Turquie", "Égypte"]', 'Grèce', 'Europe', 'Beginner', 'text'),
('Quelle ville française est célèbre pour son festival de cinéma ?', '["Cannes", "Nice", "Monaco", "Toulouse"]', 'Cannes', 'Europe', 'Beginner', 'text'),
('Quel est le pays du chocolat et des gaufres ?', '["Belgique", "Suisse", "France", "Allemagne"]', 'Belgique', 'Europe', 'Beginner', 'text'),
('La Seine traverse quelle capitale ?', '["Paris", "Londres", "Rome", "Berlin"]', 'Paris', 'Europe', 'Beginner', 'text'),
('Quel pays a pour capitale Lisbonne ?', '["Portugal", "Espagne", "Brésil", "Angola"]', 'Portugal', 'Europe', 'Beginner', 'text'),

-- Questions Débutant - Asia
('Quelle est la capitale du Japon ?', '["Tokyo", "Kyoto", "Osaka", "Séoul"]', 'Tokyo', 'Asia', 'Beginner', 'text'),
('Dans quel pays se trouve la Grande Muraille ?', '["Chine", "Japon", "Corée", "Mongolie"]', 'Chine', 'Asia', 'Beginner', 'text'),
('Quel est le pays le plus peuplé du monde (ou 2ème selon les années) ?', '["Inde", "Chine", "USA", "Indonésie"]', 'Inde', 'Asia', 'Beginner', 'text'),
('Quelle est la capitale de la Chine ?', '["Pékin", "Shanghai", "Hong Kong", "Wuhan"]', 'Pékin', 'Asia', 'Beginner', 'text'),
('Le Taj Mahal se trouve dans quel pays ?', '["Inde", "Pakistan", "Bangladesh", "Iran"]', 'Inde', 'Asia', 'Beginner', 'text'),
('Quel pays est un archipel de plus de 7000 îles ?', '["Philippines", "Japon", "Viêt Nam", "Thailande"]', 'Philippines', 'Asia', 'Beginner', 'text'),
('Quelle est la monnaie du Japon ?', '["Yen", "Won", "Yuan", "Dollar"]', 'Yen', 'Asia', 'Beginner', 'text'),
('Bangkok est la capitale de quel pays ?', '["Thaïlande", "Viêt Nam", "Cambodge", "Laos"]', 'Thaïlande', 'Asia', 'Beginner', 'text'),
('Quel pays est surnommé le Pays du Soleil Levant ?', '["Japon", "Chine", "Corée", "Thaïlande"]', 'Japon', 'Asia', 'Beginner', 'text'),
('Le Mont Everest se trouve à la frontière de quel pays et de la Chine ?', '["Népal", "Inde", "Bhoutan", "Pakistan"]', 'Népal', 'Asia', 'Beginner', 'text'),
('Quelle est la capitale de la Corée du Sud ?', '["Séoul", "Pyongyang", "Busan", "Incheon"]', 'Séoul', 'Asia', 'Beginner', 'text'),
('Quel pays a une forme de dragon (ou de S) ?', '["Viêt Nam", "Thaïlande", "Japon", "Laos"]', 'Viêt Nam', 'Asia', 'Beginner', 'text'),
('Bali est une île de quel pays ?', '["Indonésie", "Malaisie", "Philippines", "Thaïlande"]', 'Indonésie', 'Asia', 'Beginner', 'text'),
('Quel est le fleuve sacré de l''Inde ?', '["Gange", "Nil", "Amazone", "Mékong"]', 'Gange', 'Asia', 'Beginner', 'text'),

-- Questions Débutant - Americas
('Quelle est la capitale des États-Unis ?', '["Washington D.C.", "New York", "Los Angeles", "Chicago"]', 'Washington D.C.', 'Americas', 'Beginner', 'text'),
('Dans quel pays se trouve la statue du Christ Rédempteur ?', '["Brésil", "Argentine", "Mexique", "Chili"]', 'Brésil', 'Americas', 'Beginner', 'text'),
('Quel est le plus grand pays d''Amérique du Nord ?', '["Canada", "USA", "Mexique", "Groenland"]', 'Canada', 'Americas', 'Beginner', 'text'),
('Quelle est la langue principale parlée au Mexique ?', '["Espagnol", "Portugais", "Anglais", "Français"]', 'Espagnol', 'Americas', 'Beginner', 'text'),
('Ottawa est la capitale de quel pays ?', '["Canada", "USA", "Australie", "Nouvelle-Zélande"]', 'Canada', 'Americas', 'Beginner', 'text'),
('Quel pays utilise le Dollar US comme monnaie officielle ?', '["USA", "Canada", "Mexique", "Brésil"]', 'USA', 'Americas', 'Beginner', 'text'),
('La forêt amazonienne se trouve principalement dans quel pays ?', '["Brésil", "Pérou", "Colombie", "Venezuela"]', 'Brésil', 'Americas', 'Beginner', 'text'),
('Quelle ville américaine est surnommée "La Grosse Pomme" ?', '["New York", "Los Angeles", "Miami", "Chicago"]', 'New York', 'Americas', 'Beginner', 'text'),
('Quel pays est célèbre pour le sirop d''érable ?', '["Canada", "USA", "Norvège", "Finlande"]', 'Canada', 'Americas', 'Beginner', 'text'),
('Buenos Aires est la capitale de quel pays ?', '["Argentine", "Brésil", "Chili", "Uruguay"]', 'Argentine', 'Americas', 'Beginner', 'text'),
('Le Machu Picchu se trouve dans quel pays ?', '["Pérou", "Chili", "Bolivie", "Équateur"]', 'Pérou', 'Americas', 'Beginner', 'text'),
('Quel est le pays le plus long et étroit du monde ?', '["Chili", "Argentine", "Pérou", "Brésil"]', 'Chili', 'Americas', 'Beginner', 'text'),
('La Havane est la capitale de quelle île ?', '["Cuba", "Haïti", "Jamaïque", "Porto Rico"]', 'Cuba', 'Americas', 'Beginner', 'text'),
('Quel état des USA est une île dans le Pacifique ?', '["Hawaï", "Alaska", "Californie", "Floride"]', 'Hawaï', 'Americas', 'Beginner', 'text'),

-- Questions Débutant - Africa
('Quelle est la capitale de l''Égypte ?', '["Le Caire", "Alexandrie", "Louxor", "Rabat"]', 'Le Caire', 'Africa', 'Beginner', 'text'),
('Quel est le plus grand désert chaud du monde ?', '["Sahara", "Gobi", "Kalahari", "Atacama"]', 'Sahara', 'Africa', 'Beginner', 'text'),
('Dans quel pays peut-on voir les Pyramides de Gizeh ?', '["Égypte", "Soudan", "Maroc", "Tunisie"]', 'Égypte', 'Africa', 'Beginner', 'text'),
('Quel pays est complètement entouré par l''Afrique du Sud ?', '["Lesotho", "Eswatini", "Namibie", "Botswana"]', 'Lesotho', 'Africa', 'Beginner', 'text'),
('Quelle est la capitale du Maroc ?', '["Rabat", "Casablanca", "Marrakech", "Fès"]', 'Rabat', 'Africa', 'Beginner', 'text'),
('Le Kilimandjaro est le plus haut sommet de quel continent ?', '["Afrique", "Asie", "Europe", "Amérique"]', 'Afrique', 'Africa', 'Beginner', 'text'),
('Madagascar est une île située près de quel continent ?', '["Afrique", "Asie", "Océanie", "Europe"]', 'Afrique', 'Africa', 'Beginner', 'text'),
('Nelson Mandela a été président de quel pays ?', '["Afrique du Sud", "Kenya", "Nigeria", "Ghana"]', 'Afrique du Sud', 'Africa', 'Beginner', 'text'),
('Quel est le fleuve le plus long d''Afrique ?', '["Nil", "Congo", "Niger", "Zambèze"]', 'Nil', 'Africa', 'Beginner', 'text'),
('Quelle ville est célèbre pour sa place Jemaa el-Fna ?', '["Marrakech", "Le Caire", "Tunis", "Alger"]', 'Marrakech', 'Africa', 'Beginner', 'text'),
('Le Sénégal se trouve sur quel continent ?', '["Afrique", "Asie", "Amérique du Sud", "Océanie"]', 'Afrique', 'Africa', 'Beginner', 'text'),
('Quelle est la capitale du Kenya ?', '["Nairobi", "Mombasa", "Lagos", "Accra"]', 'Nairobi', 'Africa', 'Beginner', 'text'),
('Quel animal est l''emblème de la savane africaine ?', '["Lion", "Tigre", "Ours", "Loup"]', 'Lion', 'Africa', 'Beginner', 'text'),
('Quel pays forme la corne de l''Afrique ?', '["Somalie", "Éthiopie", "Soudan", "Kenya"]', 'Somalie', 'Africa', 'Beginner', 'text'),

-- Questions Débutant - Oceania
('Quelle est la capitale de l''Australie ?', '["Canberra", "Sydney", "Melbourne", "Brisbane"]', 'Canberra', 'Oceania', 'Beginner', 'text'),
('Quel animal saute et a une poche ?', '["Kangourou", "Koala", "Émeu", "Platypus"]', 'Kangourou', 'Oceania', 'Beginner', 'text'),
('La Nouvelle-Zélande est célèbre pour quel sport ?', '["Rugby", "Football", "Cricket", "Tennis"]', 'Rugby', 'Oceania', 'Beginner', 'text'),
('Sydney est une ville de quel pays ?', '["Australie", "Nouvelle-Zélande", "Fidji", "USA"]', 'Australie', 'Oceania', 'Beginner', 'text'),
('Quel est le nom des habitants de la Nouvelle-Zélande (surnom) ?', '["Kiwis", "Kangourous", "Wallabies", "Aussies"]', 'Kiwis', 'Oceania', 'Beginner', 'text'),
('Fidji se trouve dans quel océan ?', '["Pacifique", "Atlantique", "Indien", "Arctique"]', 'Pacifique', 'Oceania', 'Beginner', 'text'),
('Quelle ville australienne a un opéra en forme de voiles ?', '["Sydney", "Melbourne", "Perth", "Adélaïde"]', 'Sydney', 'Oceania', 'Beginner', 'text'),
('Quel est le plus grand pays d''Océanie ?', '["Australie", "Nouvelle-Zélande", "Papouasie", "Fidji"]', 'Australie', 'Oceania', 'Beginner', 'text'),
('La Grande Barrière de Corail est au large de quel pays ?', '["Australie", "Indonésie", "Philippines", "Japon"]', 'Australie', 'Oceania', 'Beginner', 'text'),
('Wellington est la capitale de quel pays ?', '["Nouvelle-Zélande", "Australie", "Samoa", "Tonga"]', 'Nouvelle-Zélande', 'Oceania', 'Beginner', 'text'),

-- Questions Débutant - World / General
('Combien y a-t-il de continents (modèle courant) ?', '["7", "5", "10", "3"]', '7', 'World', 'Beginner', 'text'),
('Quel est le plus grand océan du monde ?', '["Pacifique", "Atlantique", "Indien", "Arctique"]', 'Pacifique', 'World', 'Beginner', 'text'),
('Combien d''heures y a-t-il dans une journée ?', '["24", "12", "48", "60"]', '24', 'World', 'Beginner', 'text'),
('Le pôle Nord est situé dans quel océan ?', '["Arctique", "Antarctique", "Pacifique", "Indien"]', 'Arctique', 'World', 'Beginner', 'text'),
('Quel est le pays le plus vaste du monde ?', '["Russie", "Chine", "Canada", "USA"]', 'Russie', 'World', 'Beginner', 'text'),
('Quelle ligne imaginaire divise la Terre en deux hémisphères (Nord/Sud) ?', '["Équateur", "Méridien de Greenwich", "Tropique du Cancer", "Cercle Polaire"]', 'Équateur', 'World', 'Beginner', 'text'),
('Les pingouins vivent principalement où ?', '["Antarctique", "Arctique", "Sahara", "Amazonie"]', 'Antarctique', 'World', 'Beginner', 'text'),
('Quel instrument utilise-t-on pour s''orienter ?', '["Boussole", "Thermomètre", "Baromètre", "Montre"]', 'Boussole', 'World', 'Beginner', 'text'),
('Quelle langue est la plus parlée au monde (natifs) ?', '["Chinois Mandarin", "Anglais", "Espagnol", "Hindi"]', 'Chinois Mandarin', 'World', 'Beginner', 'text'),
('Quel est le sommet le plus haut du monde ?', '["Everest", "K2", "Mont Blanc", "Kilimandjaro"]', 'Everest', 'World', 'Beginner', 'text'),
('L''Antarctique est-il un continent ?', '["Oui", "Non", "Peut-être", "Seulement en hiver"]', 'Oui', 'World', 'Beginner', 'text'),
('Combien de degrés fait un angle droit ?', '["90", "180", "45", "360"]', '90', 'World', 'Beginner', 'text'),
('Quelle planète est appelée la Planète Bleue ?', '["Terre", "Mars", "Vénus", "Jupiter"]', 'Terre', 'World', 'Beginner', 'text'),
('Quel est le contraire du Nord ?', '["Sud", "Est", "Ouest", "Haut"]', 'Sud', 'World', 'Beginner', 'text'),
('Dans quelle ville se trouve le siège de l''ONU ?', '["New York", "Genève", "Paris", "Bruxelles"]', 'New York', 'World', 'Beginner', 'text'),
('La Tour Eiffel se trouve dans quel pays ?', '["France", "Italie", "Espagne", "Allemagne"]', 'France', 'World', 'Beginner', 'text'),
('Quel océan sépare l''Europe de l''Amérique ?', '["Atlantique", "Pacifique", "Indien", "Arctique"]', 'Atlantique', 'World', 'Beginner', 'text'),
('Quel est le plus grand animal du monde ?', '["Baleine bleue", "Éléphant", "Girafe", "Requin"]', 'Baleine bleue', 'World', 'Beginner', 'text'),
('Quelle est la couleur du sang ?', '["Rouge", "Bleu", "Vert", "Jaune"]', 'Rouge', 'World', 'Beginner', 'text'),
('Combien de couleurs y a-t-il dans un arc-en-ciel (traditionnellement) ?', '["7", "5", "3", "10"]', '7', 'World', 'Beginner', 'text');
